# Fix fmt 11.0.2 build failure with Xcode 26+ (upgrade to fmt 12.1.0)
# See https://github.com/facebook/react-native/pull/56099
Dir.glob("../node_modules/react-native/**/*.podspec").each do |podspec|
  next if File.basename(podspec) == 'fmt.podspec'

  content = File.read(podspec)
  patched = content.gsub(
    /\.dependency\s+["']fmt["'],\s*["']\d+\.\d+\.\d+["']/,
    '.dependency "fmt", "12.1.0"'
  )

  if patched != content
    puts "Patching fmt dependency in: #{podspec}"
    File.write(podspec, patched)
  end
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HermesCatchRepro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
